bonus: bonus.cpp 
	g++ bonus.cpp -o bonus.out -lGL -lGLU -lglut -lpthread
hw2: hw2.cpp
	g++ hw2.cpp -o a.out -lpthread
clean:
	rm -rf *.out

# main: tt.cpp 
# 	g++ tt.cpp -o tt.out -lGL -lGLU -lglut -lpthread -lGLEW -lcurses
# clean:
# 	rm -rf tt.out
